name: align_reinforce_adapter
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - lightning=2.0.8
  - portalocker
  - python=3.10
  - pytorch-cuda=11.8
  - pytorch-lightning=2.0.7
  - pip:
      - adapter-transformers==3.2.1
      - datasets
      - deepspeed==0.10.1
      - evaluate
      - konlpy
      - matplotlib
      - nltk
      - numpy==1.23.5
      - openai==0.27.8
      - pandas
      - peft
      - protobuf==3.20.3
      - python-dotenv==1.0.0
      - revtok
      - s3fs
      - sacrebleu[ko]
      - sacremoses
      - spacy
      - sentencepiece
      - torch==2.0.1
      - unbabel-comet
      - undecorated
      - wandb
      - pyyaml==6.0